# 自己的Makfile内容
# ...

# antlr的编译和链接部分
# 编译标志
CFLAGS := -I./linux_runtime/usr/local/include/antlr4-runtime #仅包含antlr4依赖
# 链接标志
LDFLAGS := -L./linux_runtime/usr/local/lib ./linux_runtime/usr/local/lib/libantlr4-runtime.a #仅包含antlr4静态链接部分 

# 自己的Makfile内容
# ...